export var COMMENT = 'comm'
export var DECLARATION = 'decl'
export var RULE = 'rule'

export var IMPORT = '@import'
export var CHARSET = '@charset'
export var NAMESPACE = '@namespace'
export var MEDIA = '@media'
export var SUPPORTS = '@supports'
export var DOCUMENT = '@document'
export var KEYFRAMES = '@keyframes'
export var PAGE = '@page'
export var FONT_FEATURE_VALUES = '@font-feature-values'

export var WEBKIT = '-webkit-'
export var MOZ = '-moz-'
export var MS = '-ms-'
