export var COMMENT = 'comment'
export var RULESET = 'ruleset'
export var DECLARATION = 'declaration'

export var PAGE = '@page'
export var MEDIA = '@media'
export var IMPORT = '@import'
export var CHARSET = '@charset'
export var VIEWPORT = '@viewport'
export var SUPPORTS = '@supports'
export var DOCUMENT = '@document'
export var NAMESPACE = '@namespace'
export var FONT_FACE = '@font-face'
export var KEYFRAMES = '@keyframes'
export var COUNTER_STYLE = '@counter-style'
export var FONT_FEATURE_VALUES = '@font-feature-values'

export var MS = '-ms-'
export var MOZ = '-moz-'
export var WEBKIT = '-webkit-'
